name: Image Lambda CI

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "requirements.txt"
      - "Dockerfile"
      - "infra/image/**"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: sa-east-1
      REPO_NAME: artifact-fn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin "$(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_REGION.amazonaws.com"

      - name: Descobrir URI do repositório
        id: repo
        run: |
          URI=$(aws ecr describe-repositories --repository-names "$REPO_NAME" --query 'repositories[0].repositoryUri' --output text)
          echo "uri=$URI" >> $GITHUB_OUTPUT

      - name: Build & Push da imagem
        env:
          REPO_URI: ${{ steps.repo.outputs.uri }}
          GIT_SHA: ${{ github.sha }}
        run: |
          SHORT=${GIT_SHA::7}
          docker build -t "$REPO_URI:$SHORT" -f infra/image/Dockerfile infra/image
          docker push "$REPO_URI:$SHORT"
          echo "TAG=$SHORT" >> $GITHUB_ENV

      # >>> Estes são os passos a que eu me referia <<<
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init (image)
        working-directory: infra/image
        run: terraform init -upgrade

      - name: Terraform Apply (image)
        working-directory: infra/image
        run: |
          terraform apply \
            -auto-approve \
            -input=false \
            -lock-timeout=5m \
            -var="image_tag=TAG"