name: Layer CI

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "requirements.txt"
      - "pyproject.toml"
      - "infra/**"
      - "scripts/**"
      - "Makefile"
  workflow_dispatch: {}

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: sa-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Layer
        run: make build

      - name: Configure AWS (static)
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.7.5   # ou a versão que você quiser
            # cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
      - name: Terraform Plan
        run: make plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: make apply

      - name: Outputs
        run: make output
