name: Layer CI

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "scripts/build_layer.sh"
      - "scripts/build_arrow_layer.sh"         # <— novo
      - "requirements-layer.txt"
      - "requirements-layer-arrow.txt"         # <— novo
      - "infra/layer/**"
  workflow_dispatch: {}

jobs:
  build-layer:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: sa-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build layer.zip (CORE)
        run: bash scripts/build_layer.sh

      - name: Build arrow_layer.zip (ARROW)
        run: bash scripts/build_arrow_layer.sh

      - name: Mover zips para o módulo Terraform
        run: |
          mkdir -p infra/layer/dist
          cp layer.zip infra/layer/dist/core_layer.zip
          cp arrow_layer.zip infra/layer/dist/arrow_layer.zip

      - name: Conferir tamanhos e existência
        run: |
          ls -lah infra/layer/dist
          du -sh infra/layer/dist/* || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra/layer
        run: terraform init -upgrade

      - name: Terraform Apply (publica layers core + arrow)
        working-directory: infra/layer
        run: terraform apply -auto-approve

      - name: Outputs
        working-directory: infra/layer
        run: terraform output
